#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SeniorenApp.Resource", IsApplication=true)]

namespace SeniorenApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about128 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CameraToRead128 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contactList128 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int phonereceiver128 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int AboutActivity = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int ButtonClear = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int ButtonEight = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int ButtonFive = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int ButtonFour = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int ButtonNine = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int ButtonOne = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int ButtonRemove = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int ButtonSeven = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int ButtonSix = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int ButtonThree = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int ButtonTwo = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int ButtonZero = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int CallActivity = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int CameraActivity = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int ContactListActivity = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int ContactsList = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int GoBack = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int LinearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int MakeCall = 2131099671;
			
			// aapt resource value: 0x7f060003
			public const int Name = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int PhoneNumber = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int Preview = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int info_text = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Camera = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactsListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactsListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ManualCall = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int BackButtonText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CallActivityText = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int ClearNumberText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int DeleteCharacterText = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int OpenAboutActivityText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int OpenCameraActivityText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int OpenContactsActivityText = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int StartCallText = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int accessory_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
